import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import Image from 'next/image';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Complaint Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
    <body>
    <div className="navbar bg-custom-primary text-primary-content p-4 flex justify-between items-center">
      <p className="normal-case text-xl">Attendant</p>
      <div className="flex items-center space-x-4">
        <Link href="/Attendant" className="text-white">
          ReportList
        </Link>
        <Link href="/Notification" className="text-white">
          Notification
        </Link>
        <Link href="/profile">
          <Image
            src="/avatar.png"
            alt="Description of the image"
            width={50}
            height={50}
            className="rounded-full"
          />
        </Link>
      </div>
    </div>

    <div>{children}</div>
    </body>
  </html>
  )
}
