import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ProtectedRoute from "./components/RouteProtection";
import SessionProvider from "./components/SessionProvider";
import { getServerSession } from "next-auth";
import { AuthProvider } from "./context/auth";
import BlockRoute from "./components/blocker";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hostel Management App",
  description: "Generated by Admin",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <AuthProvider>
            <ProtectedRoute>{children}</ProtectedRoute>
          </AuthProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
